# Generated by Django 6.0.5 on 2026-05-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "tmdb_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
                ("overview", models.TextField(blank=True)),
                ("vote_average", models.FloatField(blank=True, null=True)),
                ("vote_count", models.IntegerField(default=0)),
                ("popularity", models.FloatField(default=0.0)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("valence", models.FloatField(blank=True, null=True)),
                ("arousal", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-popularity"],
            },
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(blank=True, max_length=255, null=True)),
                ("source_tag", models.CharField(blank=True, max_length=100, null=True)),
                ("listeners", models.IntegerField(default=0)),
                ("playcount", models.IntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("emotion_vector", models.JSONField(default=dict)),
                ("valence", models.FloatField(blank=True, null=True)),
                ("arousal", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-playcount"],
            },
        ),
    ]
