# Generated by Django 6.0.5 on 2026-05-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster_path',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='emotion_vector',
            field=models.JSONField(default=dict),
        ),
    ]
