# Generated by Django 6.0.5 on 2026-05-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
