# Generated by Django 6.0.5 on 2026-05-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_movie', '0002_rename_poster_path_movie_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='anger',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fear',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='joy',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='sadness',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='surprise',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trust',
        ),
        migrations.RemoveField(
            model_name='music',
            name='anger',
        ),
        migrations.RemoveField(
            model_name='music',
            name='fear',
        ),
        migrations.RemoveField(
            model_name='music',
            name='joy',
        ),
        migrations.RemoveField(
            model_name='music',
            name='sadness',
        ),
        migrations.RemoveField(
            model_name='music',
            name='surprise',
        ),
        migrations.RemoveField(
            model_name='music',
            name='trust',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='emotion_vector',
            field=models.JSONField(default=dict),
        ),
    ]
