# Generated by Django 6.0.5 on 2026-05-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_movie', '0002_remove_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
