# Generated by Django 6.0.5 on 2026-05-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_movie', '0003_remove_movie_anger_remove_movie_fear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image_url',
            new_name='poster_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='emotion_vector',
        ),
        migrations.RemoveField(
            model_name='music',
            name='emotion_vector',
        ),
        migrations.AddField(
            model_name='movie',
            name='anger',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='fear',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='joy',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='sadness',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='surprise',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trust',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='anger',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='fear',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='joy',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='sadness',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='surprise',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='trust',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
