"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ, os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables early
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))  # load .env for local development


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment for deployment; fallback to a dev key for local testing
SECRET_KEY = env('SECRET_KEY', default='django-insecure-devlocalkey')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

# ALLOWED_HOSTS: allow '*' or comma-separated list in .env
_allowed = env('ALLOWED_HOSTS', default='*')
if _allowed.strip() == '*':
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages', 
    'django.contrib.staticfiles',
    'rest_framework',              # DRF
    'rest_framework.authtoken',    # DRF 토큰 인증
    'drf_yasg',                    # Swagger/Redoc
    'corsheaders',                 # CORS
    
    # daybydaybackend 앱 (기능별 분리)
    'daybydaybackend.accounts.apps.AccountsConfig',  # 인증
    'daybydaybackend.diary.apps.DiaryConfig',        # 일기 & 감정 분석
    'daybydaybackend.books.apps.BooksConfig',        # 도서 추천
    'daybydaybackend.music_movie.apps.MusicMovieConfig',  # 음악/영화 추천
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 맨 위쪽에 추가
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 정적 파일 서빙용 whitenoise 미들웨어
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

IS_RENDER = 'RENDER' in os.environ

if IS_RENDER:
    # Render 무료 티어 환경: 디스크가 없으므로 서버 임시 보존 경로 사용 (재배포 시 데이터 리셋됨)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # 로컬 개발 환경
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 배포 시 static 파일들을 모을 경로

# 정적 파일 저장을 위한 Whitenoise 압축/캐싱 설정
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings: support allow-all flag or explicit origins via .env
# Set CORS_ALLOW_ALL_ORIGINS=True in .env to allow any origin (only for dev/demo)
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)
if CORS_ALLOW_ALL_ORIGINS:
    # django-cors-headers: when True, all origins are allowed
    CORS_ALLOWED_ORIGINS = []
else:
    CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=['http://localhost:3000'])

# DRF 기본 설정: 토큰 인증 사용
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# Swagger(drf-yasg) 보안 설정: 토큰 방식 인증 UI 활성화
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': DEBUG,  # 세션 인증 비활성화 (토큰 인증만 사용)
    'DEFAULT_MODEL_RENDERING': 'example',
    'SECURITY_DEFINITIONS': {
        'Token': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': "로그인 후 발급받은 Token을 입력하세요(중요! Token 앞에 'Token '을 붙여야 합니다. 예: 'Token abcdef123456')"
        }
    }
}

# ===== API 키 설정 =====
# Gemini API KEY (일기 감정 분석용)
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')
GEMINI_MODEL = env('GEMINI_MODEL', default='gemini-2.5-flash')

# Aladin TTB API KEY (도서 추천용)
ALADIN_TTB_KEY = env('ALADIN_TTB_KEY', default='')

# LLM API KEY (책 감정 태깅용 - Gemini)
LLM_API_KEY = env('GEMINI_API_KEY', default='')

# ===== 미디어 파일 저장 설정 =====
MEDIA_URL = '/media/'

if IS_RENDER:
    # Render 무료 티어 환경: 임시 미디어 보존 경로 사용
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'


