# Generated by Django 6.0.5 on 2026-05-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('reviews', models.TextField(blank=True)),
                ('valence', models.FloatField(blank=True, null=True)),
                ('arousal', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
