# Generated by Django 6.0.5 on 2026-05-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviews',
        ),
        migrations.AddField(
            model_name='book',
            name='is_review_crawled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
