# Generated by Django 6.0.5 on 2026-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_reviews_book_is_review_crawled_book_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='anger',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='fear',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='joy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sadness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='surprise',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
