# Generated by Django 6.0.5 on 2026-05-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_anger_book_fear_book_joy_book_sadness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='trust',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
