# Generated by Django 6.0.5 on 2026-05-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_recommendationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendationLog',
        ),
    ]
