# Generated by Django 6.0.5 on 2026-05-13 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiaryEmotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valence",
                    models.FloatField(
                        help_text="감정의 긍정/부정 정도를 나타내는 값 (-1.0에서 1.0 사이)"
                    ),
                ),
                (
                    "arousal",
                    models.FloatField(
                        help_text="감정의 활성화 정도를 나타내는 값 (-1.0에서 1.0 사이)"
                    ),
                ),
                (
                    "primary_emotion",
                    models.CharField(
                        default="알수없음", help_text="대표 감정 단어", max_length=50
                    ),
                ),
                (
                    "diary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emotion",
                        to="diary.diary",
                    ),
                ),
            ],
        ),
    ]
