# Generated by Django 6.0.5 on 2026-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecommended',
            name='mode',
            field=models.CharField(default='maintain', help_text='추천이 생성된 감정 모드', max_length=20),
        ),
    ]
