# Generated by Django 6.0.5 on 2026-05-28 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("diary", "0001_initial"),
        ("music_movie", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_like",
                    models.BooleanField(help_text="True: 좋아요, False: 싫어요"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="books.book",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="music_movie.movie",
                    ),
                ),
                (
                    "music",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="music_movie.music",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("book__isnull", False)),
                        fields=("user", "book"),
                        name="unique_user_book_feedback",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("music__isnull", False)),
                        fields=("user", "music"),
                        name="unique_user_music_feedback",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("movie__isnull", False)),
                        fields=("user", "movie"),
                        name="unique_user_movie_feedback",
                    ),
                ],
            },
        ),
    ]
