# Generated by Django 6.0.5 on 2026-05-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_expand_diaryemotion_to_6d"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="일기에 첨부된 사진",
                null=True,
                upload_to="diaries/",
            ),
        ),
        migrations.AddField(
            model_name="diary",
            name="weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "맑음"),
                    ("CLOUDY", "흐림"),
                    ("RAINY", "비"),
                    ("SNOWY", "눈"),
                    ("WINDY", "바람"),
                    ("THUNDER", "천둥"),
                ],
                help_text="일기 작성 당시 날씨",
                max_length=10,
                null=True,
            ),
        ),
    ]
