# Generated by Django 6.0.5 on 2026-05-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_recommendationlog'),
        ('diary', '0002_expand_diaryemotion_to_6d'),
        ('music_movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_contents', to='diary.diary')),
                ('recommended_books', models.ManyToManyField(related_name='daily_book_recommendations', to='books.book')),
                ('recommended_movies', models.ManyToManyField(related_name='daily_movie_recommendations', to='music_movie.movie')),
                ('recommended_music', models.ManyToManyField(related_name='daily_music_recommendations', to='music_movie.music')),
            ],
        ),
    ]
