# Generated by Django 6.0.5 on 2026-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_recommendationlog'),
        ('diary', '0003_dailyrecommended'),
        ('music_movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecommended',
            name='recommended_books',
        ),
        migrations.RemoveField(
            model_name='dailyrecommended',
            name='recommended_movies',
        ),
        migrations.RemoveField(
            model_name='dailyrecommended',
            name='recommended_music',
        ),
        migrations.AddField(
            model_name='dailyrecommended',
            name='books',
            field=models.ManyToManyField(related_name='daily_book', to='books.book'),
        ),
        migrations.AddField(
            model_name='dailyrecommended',
            name='movies',
            field=models.ManyToManyField(related_name='daily_movie', to='music_movie.movie'),
        ),
        migrations.AddField(
            model_name='dailyrecommended',
            name='music',
            field=models.ManyToManyField(related_name='daily_music', to='music_movie.music'),
        ),
    ]
