# Generated by Copilot on 2026-05-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_diary_image_diary_weather"),
        ("music_movie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRecommended",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommended_music",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="추천 음악 제목",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "recommended_movie",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="추천 영화 제목",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "diary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="diary.diary",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dailyrecommended",
            name="movies",
            field=models.ManyToManyField(
                blank=True,
                related_name="daily_recommendations",
                to="music_movie.movie",
            ),
        ),
        migrations.AddField(
            model_name="dailyrecommended",
            name="music",
            field=models.ManyToManyField(
                blank=True,
                related_name="daily_recommendations",
                to="music_movie.music",
            ),
        ),
    ]