# Generated by Copilot on 2026-05-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_dailyrecommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecommended',
            name='recommended_music',
        ),
        migrations.RemoveField(
            model_name='dailyrecommended',
            name='recommended_movie',
        ),
    ]