# Generated by Django 6.0.5 on 2026-05-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0004_remove_dailyrecommended_recommended_books_and_more"),
        ("diary", "0006_alter_diary_user"),
    ]

    operations = []
