# Generated by Django 6.0.5 on 2026-05-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_delete_recommendationlog"),
        ("diary", "0007_merge_20260524_1521"),
        ("music_movie", "0002_music_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyrecommended",
            name="books",
            field=models.ManyToManyField(
                blank=True, related_name="daily_recommendations", to="books.book"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrecommended",
            name="diary",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation",
                to="diary.diary",
            ),
        ),
        migrations.AlterField(
            model_name="dailyrecommended",
            name="movies",
            field=models.ManyToManyField(
                blank=True, related_name="daily_recommendations", to="music_movie.movie"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrecommended",
            name="music",
            field=models.ManyToManyField(
                blank=True, related_name="daily_recommendations", to="music_movie.music"
            ),
        ),
    ]
